# Signals to include when saving to CSV/pkl. All other logged signals are
# available in memory (logger.output) but not written to file.
- position
- q
- v
- dv
- f_ctrl_input
- torque_ctrl_input
- f_disturb
- torque_disturb
- omega
- omega_dot
- rotor_0_rotation_spd
- rotor_1_rotation_spd
- rotor_2_rotation_spd
- rotor_3_rotation_spd
- rotor_0_position
- rotor_1_position
- rotor_2_position
- rotor_3_position
- rotor_0_velocity
- rotor_1_velocity
- rotor_2_velocity
- rotor_3_velocity
- f_disturb_sensed_raw
- rotor_0_local_wind_velocity
- rotor_1_local_wind_velocity
- rotor_2_local_wind_velocity
- rotor_3_local_wind_velocity
- rotor_0_sensed_wind_velocity
- rotor_1_sensed_wind_velocity
- rotor_2_sensed_wind_velocity
- rotor_3_sensed_wind_velocity
- rotor_0_f_rotor_inertial_frame
- rotor_1_f_rotor_inertial_frame
- rotor_2_f_rotor_inertial_frame
- rotor_3_f_rotor_inertial_frame
- rotor_0_thrust
- rotor_1_thrust
- rotor_2_thrust
- rotor_3_thrust
- shared_r_disk
- sensed_dv
- sensed_omega
- rotor_speeds_desired
